apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-nfs-deploy
  labels:
    app: nginx-nfs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginx-nfs
  template:
    metadata:
     name: nginx-pod
     labels:
       app: nginx-nfs
    spec:
      volumes:
        - name: unity-nfs-volume
          persistentVolumeClaim:
            claimName: pvc-unity-nfs
      containers:
      - name: nginx-container
        image: nginxdemos/hello
        ports:
          - containerPort: 80
        volumeMounts:
          - mountPath: "/export/nginx"
            name: unity-nfs-volume
        securityContext:
          allowPrivilegeEscalation: true
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nfs-service
  labels:
    name: nginx-nfs
spec:
  type: NodePort
  selector:
    app: nginx-nfs
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30008
