apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-unity-clone
spec:
  storageClassName: unity-iscsi
  dataSource:
    name: pvc-unity
    kind: PersistentVolumeClaim
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
